// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'unified_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UnifiedDetailImpl _$$UnifiedDetailImplFromJson(Map<String, dynamic> json) =>
    _$UnifiedDetailImpl(
      contentId: (json['contentId'] as num).toInt(),
      contentType: $enumDecode(_$ContentTypeEnumMap, json['contentType']),
      infoCenter: json['infoCenter'] as String,
      openTime: json['openTime'] as String,
      useFee: json['useFee'] as String,
      useTime: json['useTime'] as String,
      restDay: json['restDay'] as String,
      parking: json['parking'] as String,
      firstMenu: json['firstMenu'] as String,
      treatMenu: json['treatMenu'] as String,
      spendTime: json['spendTime'] as String,
      playTime: json['playTime'] as String,
      petAllowed: json['petAllowed'] as String,
      startDate: json['startDate'] as String,
      endDate: json['endDate'] as String,
      sponsor: json['sponsor'] as String,
      sponsorTel: json['sponsorTel'] as String,
      homePage: json['homePage'] as String,
      ageLimit: json['ageLimit'] as String,
      placeInfo: json['placeInfo'] as String,
      reservationUrl: json['reservationUrl'] as String,
      roomCount: json['roomCount'] as String,
      pickup: json['pickup'] as String,
      park: json['park'] as String,
      subFacility: json['subFacility'] as String,
      foodPlace: json['foodPlace'] as String,
      takeTime: json['takeTime'] as String,
      saleItem: json['saleItem'] as String,
      saleItemCost: json['saleItemCost'] as String,
      scale: json['scale'] as String,
      creditCard: json['creditCard'] as String,
      distance: json['distance'] as String,
      expGuide: json['expGuide'] as String,
      isGoodStay: json['isGoodStay'] as bool,
      isBenikia: json['isBenikia'] as bool,
      isHanok: json['isHanok'] as bool,
      hasSeminar: json['hasSeminar'] as bool,
      hasSports: json['hasSports'] as bool,
      hasSauna: json['hasSauna'] as bool,
      hasBeauty: json['hasBeauty'] as bool,
      hasBeverage: json['hasBeverage'] as bool,
      hasKaraoke: json['hasKaraoke'] as bool,
      hasBarbecue: json['hasBarbecue'] as bool,
      hasCampfire: json['hasCampfire'] as bool,
      hasBicycle: json['hasBicycle'] as bool,
      hasFitness: json['hasFitness'] as bool,
      hasPublicPc: json['hasPublicPc'] as bool,
      hasPublicBath: json['hasPublicBath'] as bool,
    );

Map<String, dynamic> _$$UnifiedDetailImplToJson(_$UnifiedDetailImpl instance) =>
    <String, dynamic>{
      'contentId': instance.contentId,
      'contentType': _$ContentTypeEnumMap[instance.contentType]!,
      'infoCenter': instance.infoCenter,
      'openTime': instance.openTime,
      'useFee': instance.useFee,
      'useTime': instance.useTime,
      'restDay': instance.restDay,
      'parking': instance.parking,
      'firstMenu': instance.firstMenu,
      'treatMenu': instance.treatMenu,
      'spendTime': instance.spendTime,
      'playTime': instance.playTime,
      'petAllowed': instance.petAllowed,
      'startDate': instance.startDate,
      'endDate': instance.endDate,
      'sponsor': instance.sponsor,
      'sponsorTel': instance.sponsorTel,
      'homePage': instance.homePage,
      'ageLimit': instance.ageLimit,
      'placeInfo': instance.placeInfo,
      'reservationUrl': instance.reservationUrl,
      'roomCount': instance.roomCount,
      'pickup': instance.pickup,
      'park': instance.park,
      'subFacility': instance.subFacility,
      'foodPlace': instance.foodPlace,
      'takeTime': instance.takeTime,
      'saleItem': instance.saleItem,
      'saleItemCost': instance.saleItemCost,
      'scale': instance.scale,
      'creditCard': instance.creditCard,
      'distance': instance.distance,
      'expGuide': instance.expGuide,
      'isGoodStay': instance.isGoodStay,
      'isBenikia': instance.isBenikia,
      'isHanok': instance.isHanok,
      'hasSeminar': instance.hasSeminar,
      'hasSports': instance.hasSports,
      'hasSauna': instance.hasSauna,
      'hasBeauty': instance.hasBeauty,
      'hasBeverage': instance.hasBeverage,
      'hasKaraoke': instance.hasKaraoke,
      'hasBarbecue': instance.hasBarbecue,
      'hasCampfire': instance.hasCampfire,
      'hasBicycle': instance.hasBicycle,
      'hasFitness': instance.hasFitness,
      'hasPublicPc': instance.hasPublicPc,
      'hasPublicBath': instance.hasPublicBath,
    };

const _$ContentTypeEnumMap = {
  ContentType.all: 'all',
  ContentType.touristSpot: 'touristSpot',
  ContentType.cultureLocation: 'cultureLocation',
  ContentType.festival: 'festival',
  ContentType.course: 'course',
  ContentType.leports: 'leports',
  ContentType.lodgment: 'lodgment',
  ContentType.shopping: 'shopping',
  ContentType.restaurant: 'restaurant',
};
